# travisci configuration for coverage testing 
dist: jammy
language: node_js
node_js:
  - "18"  # Specify the version of Node.js you want to use

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

